import { Flag } from '@keira/shared/constants';

export const MECHANIC_IMMUNE_MASK: Flag[] = [
  { bit: 0, name: '魅惑' },
  { bit: 1, name: '迷惑' },
  { bit: 2, name: '缴械' },
  { bit: 3, name: '分散注意' },
  { bit: 4, name: '恐惧' },
  { bit: 5, name: '死亡之握及类似效果' },
  { bit: 6, name: '定身' },
  { bit: 7, name: '攻击减速' },
  { bit: 8, name: '沉默' },
  { bit: 9, name: '昏睡' },
  { bit: 10, name: '减速' },
  { bit: 11, name: '昏迷' },
  { bit: 12, name: '冰冻' },
  { bit: 13, name: '击倒 - 如圣骑士的忏悔等定身效果' },
  { bit: 14, name: '流血' },
  { bit: 15, name: '绷带 - 治疗' },
  { bit: 16, name: '变形' },
  { bit: 17, name: '放逐' },
  { bit: 18, name: '护盾' },
  { bit: 19, name: '束缚亡灵 - 仅限束缚亡灵法术' },
  { bit: 20, name: '坐骑 - 任何召唤坐骑的效果' },
  { bit: 21, name: '感染 - 如冰霜疫病、血之疫病等' },
  { bit: 22, name: '恐惧不死生物 - 如超度邪恶' },
  { bit: 23, name: '恐惧术 - 如术士的死亡缠绕' },
  { bit: 24, name: '无敌 - 自律、虚空防护、外交豁免等' },
  { bit: 25, name: '打断' },
  { bit: 26, name: '眩晕' },
  { bit: 27, name: '制造物品 - 任何创造物品的效果' },
  { bit: 28, name: '免疫护盾 - 如圣盾术、寒冰屏障、保护之手' },
  { bit: 29, name: '闷棍' },
  { bit: 30, name: '狂暴' },
];
