import { CREATURE_TYPE } from '../options/creature-type';
import { Flag } from '@keira/shared/constants';

export const SPELL_DBC_CREATURE_TYPE_FLAGS: Flag[] = CREATURE_TYPE.slice(1, CREATURE_TYPE.length).map((option) => ({
  bit: (option.value as number) - 1,
  name: option.name,
}));

export const SPELL_DBC_FACING_FRONT_FLAG: Flag[] = [{ bit: 0, name: '面向前方' }];

export const SPELL_DBC_INTERRUPT_FLAGS: Flag[] = [
  { bit: 0, name: '移动时' },
  { bit: 1, name: '击退时' },
  { bit: 2, name: '施法被打断时' },
  { bit: 3, name: '法术系被打断时' },
  { bit: 4, name: '受到伤害时' },
  { bit: 5, name: '所有打断时' },
];

export const SPELL_DBC_AURA_INTERRUPT_FLAGS: Flag[] = [
  { bit: 0, name: '被法术击中时' },
  { bit: 1, name: '受到伤害时' },
  { bit: 2, name: '施法时' },
  { bit: 3, name: '移动时' },
  { bit: 4, name: '转向时' },
  { bit: 5, name: '跳跃时' },
  { bit: 6, name: '未骑乘时' },
  { bit: 7, name: '不在水面上时' },
  { bit: 8, name: '不在水下时' },
  { bit: 9, name: '未收武器时' },
  { bit: 10, name: '交谈时' },
  { bit: 11, name: '使用时' },
  { bit: 12, name: '近战攻击时' },
  { bit: 13, name: '法术攻击时' },
  { bit: 14, name: '未知' },
  { bit: 15, name: '变形时' },
  { bit: 16, name: '未知' },
  { bit: 17, name: '骑乘时' },
  { bit: 18, name: '未坐下时' },
  { bit: 19, name: '切换地图时' },
  { bit: 20, name: '免疫或失去选择时' },
  { bit: 21, name: '未知' },
  { bit: 22, name: '传送时' },
  { bit: 23, name: '进入PvP战斗时' },
  { bit: 24, name: '受到直接伤害时' },
  { bit: 25, name: '着陆时' },
];

export const SPELL_DBC_STANCES_FLAGS: Flag[] = [
  { bit: 0, name: '猎豹形态' },
  { bit: 1, name: '树形态' },
  { bit: 2, name: '旅行形态' },
  { bit: 3, name: '水栖形态' },
  { bit: 4, name: '熊形态' },
  { bit: 5, name: '环境形态' },
  { bit: 6, name: '食尸鬼形态' },
  { bit: 7, name: '巨熊形态' },
  { bit: 8, name: '史蒂夫食尸鬼' },
  { bit: 9, name: '萨隆加骷髅' },
  { bit: 10, name: '力量测试' },
  { bit: 11, name: 'BLB玩家' },
  { bit: 12, name: '暗影之舞' },
  { bit: 13, name: '生物熊形态' },
  { bit: 14, name: '生物猫形态' },
  { bit: 15, name: '幽魂之狼' },
  { bit: 16, name: '战斗姿态' },
  { bit: 17, name: '防御姿态' },
  { bit: 18, name: '狂暴姿态' },
  { bit: 19, name: '测试' },
  { bit: 20, name: '僵尸' },
  { bit: 21, name: '恶魔变形' },
  { bit: 22, name: '亡灵' },
  { bit: 23, name: '钓鱼大师' },
  { bit: 24, name: '飞行（史诗）' },
  { bit: 25, name: '暗影' },
  { bit: 26, name: '飞行（普通）' },
  { bit: 27, name: '潜行' },
  { bit: 28, name: '枭兽形态' },
  { bit: 29, name: '救赎之魂' },
];

export const SPELL_DBC_CHANNEL_INTERRUPT_FLAGS: Flag[] = [
  { bit: 0, name: '条件1' },
  { bit: 1, name: '条件2' },
  { bit: 2, name: '条件3' },
  { bit: 3, name: '条件4' },
  { bit: 4, name: '条件5' },
  { bit: 5, name: '条件6' },
  { bit: 6, name: '条件7' },
  { bit: 7, name: '条件8' },
  { bit: 8, name: '条件9' },
  { bit: 9, name: '条件10' },
  { bit: 10, name: '条件11' },
  { bit: 11, name: '条件12' },
  { bit: 12, name: '条件13' },
  { bit: 13, name: '条件14' },
  { bit: 14, name: '条件15' },
  { bit: 15, name: '条件16' },
  { bit: 16, name: '条件17' },
  { bit: 17, name: '条件18' },
];

export const SPELL_DBC_ATTRIBUTES_FLAGS: { [key: string]: Flag[] } = {};

SPELL_DBC_ATTRIBUTES_FLAGS[''] = [
  { bit: 0, name: '触发失败消耗充能' },
  { bit: 1, name: '使用远程武器栏' },
  { bit: 2, name: '下次攻击时（伤害无关）' },
  { bit: 3, name: '不记录免疫未命中' },
  { bit: 4, name: '是技能' },
  { bit: 5, name: '是商业技能' },
  { bit: 6, name: '被动' },
  { bit: 7, name: '不显示（法术书、光环图标、战斗记录）' },
  { bit: 8, name: '不记录' },
  { bit: 9, name: '仅限持有物品' },
  { bit: 10, name: '下次攻击时' },
  { bit: 11, name: '装备者施放触发' },
  { bit: 12, name: '仅限服务器' },
  { bit: 13, name: '允许PvP中的物品法术' },
  { bit: 14, name: '仅限室内' },
  { bit: 15, name: '仅限室外' },
  { bit: 16, name: '非变形状态' },
  { bit: 17, name: '仅限潜行状态' },
  { bit: 18, name: '不收武器' },
  { bit: 19, name: '法术伤害随等级缩放' },
  { bit: 20, name: '取消自动攻击战斗' },
  { bit: 21, name: '无法闪避、招架或格挡' },
  { bit: 22, name: '施法时追踪目标' },
  { bit: 23, name: '死亡时可施放' },
  { bit: 24, name: '骑乘时可施放' },
  { bit: 25, name: '光环消失后开始冷却' },
  { bit: 26, name: '负面效果/光环是减益效果' },
  { bit: 27, name: '坐下时可施放' },
  { bit: 28, name: '战斗中无法使用' },
  { bit: 29, name: '不受无敌影响' },
  { bit: 30, name: '受伤害打断' },
  { bit: 31, name: '光环无法被取消' },
];

SPELL_DBC_ATTRIBUTES_FLAGS['Ex'] = [
  { bit: 0, name: '先解散宠物' },
  { bit: 1, name: '消耗所有能量' },
  { bit: 2, name: '是引导法术' },
  { bit: 3, name: '无法被重定向' },
  { bit: 4, name: '无技能提升' },
  { bit: 5, name: '潜行时允许' },
  { bit: 6, name: '是自我引导' },
  { bit: 7, name: '无法被反射' },
  { bit: 8, name: '战斗中无法选择目标' },
  { bit: 9, name: '开始战斗（启用自动攻击）' },
  { bit: 10, name: '不产生威胁值' },
  { bit: 11, name: '光环唯一' },
  { bit: 12, name: '失败打破潜行' },
  { bit: 13, name: '远视' },
  { bit: 14, name: '引导时追踪目标' },
  { bit: 15, name: '免疫时移除光环' },
  { bit: 16, name: '对敌对和友方效果免疫' },
  { bit: 17, name: '无自动施法（仅AI）' },
  { bit: 18, name: '阻止动画' },
  { bit: 19, name: '无法以自身为目标' },
  { bit: 20, name: '终结技 - 伤害' },
  { bit: 21, name: '仅未命中时产生威胁' },
  { bit: 22, name: '终结技 - 持续时间' },
  { bit: 23, name: '忽略所有者死亡' },
  { bit: 24, name: '特殊技能提升' },
  { bit: 25, name: '战斗后保留光环' },
  { bit: 26, name: '需要所有目标' },
  { bit: 27, name: '未命中时折扣能量' },
  { bit: 28, name: '光环栏中隐藏' },
  { bit: 29, name: '频道栏中显示名称' },
  { bit: 30, name: '闪避时启用法术/格挡时连击' },
  { bit: 31, name: '学习时施放' },
];

SPELL_DBC_ATTRIBUTES_FLAGS['Ex2'] = [
  { bit: 0, name: '可选择死亡单位或尸体' },
  { bit: 1, name: '无变形界面' },
  { bit: 2, name: '忽略视线' },
  { bit: 3, name: '允许低等级增益' },
  { bit: 4, name: '显示在姿态栏/使用变形栏' },
  { bit: 5, name: '自动重复' },
  { bit: 6, name: '需要未被攻击的目标' },
  { bit: 7, name: '不报告法术失败' },
  { bit: 8, name: '包含在高级战斗记录中' },
  { bit: 9, name: '始终作为单位施放' },
  { bit: 10, name: '特殊驯服标记' },
  { bit: 11, name: '无目标每秒消耗' },
  { bit: 12, name: '从施法者连锁' },
  { bit: 13, name: '竞技场中保留附魔' },
  { bit: 14, name: '隐形时允许' },
  { bit: 15, name: '施法获得时不消耗' },
  { bit: 16, name: '无激活宠物' },
  { bit: 17, name: '不重置战斗计时器' },
  { bit: 18, name: '需要死亡宠物/施法待定时不跳跃' },
  { bit: 19, name: '不需要变形' },
  { bit: 20, name: '施法后开始战斗（启用自动攻击）' },
  { bit: 21, name: '所有目标免疫时失败' },
  { bit: 22, name: '无初始威胁' },
  { bit: 23, name: '失败时触发冷却' },
  { bit: 24, name: '使用所有者技能施放物品' },
  { bit: 25, name: '不阻止法力回复' },
  { bit: 26, name: '无法术系免疫' },
  { bit: 27, name: '忽略武器技能' },
  { bit: 28, name: '不是动作' },
  { bit: 29, name: '无法暴击' },
  { bit: 30, name: '主动威胁' },
  { bit: 31, name: '保留物品施放' },
];

SPELL_DBC_ATTRIBUTES_FLAGS['Ex3'] = [
  { bit: 0, name: '启用PvP' },
  { bit: 1, name: '无装备需求触发' },
  { bit: 2, name: '无施法条文字' },
  { bit: 3, name: '可被格挡/完全格挡' },
  { bit: 4, name: '忽略复活计时器' },
  { bit: 5, name: '无耐久度损失' },
  { bit: 6, name: '无法躲闪' },
  { bit: 7, name: '不同施法者可叠加' },
  { bit: 8, name: '仅限玩家目标' },
  { bit: 9, name: '非触发效果' },
  { bit: 10, name: '需要主手武器' },
  { bit: 11, name: '仅限战场' },
  { bit: 12, name: '仅限灵魂目标' },
  { bit: 13, name: '隐藏引导条' },
  { bit: 14, name: '在团队过滤中隐藏' },
  { bit: 15, name: '普通远程攻击（自动射击）' },
  { bit: 16, name: '抑制施法者触发' },
  { bit: 17, name: '抑制目标触发' },
  { bit: 18, name: '无法未命中' },
  { bit: 19, name: '禁用触发/即时目标触发' },
  { bit: 20, name: '死亡后持续' },
  { bit: 21, name: '仅在室外触发' },
  { bit: 22, name: '施法取消自动重复' },
  { bit: 23, name: '无伤害历史' },
  { bit: 24, name: '需要副手武器' },
  { bit: 25, name: '视为周期性效果' },
  { bit: 26, name: '可从触发效果中触发' },
  { bit: 27, name: '仅对施法者触发' },
  { bit: 28, name: '忽略施法者和目标限制' },
  { bit: 29, name: '忽略施法者修正' },
  { bit: 30, name: '不在提示中显示范围' },
  { bit: 31, name: '不受范围伤害免疫影响' },
];

SPELL_DBC_ATTRIBUTES_FLAGS['Ex4'] = [
  { bit: 0, name: '忽略所有抗性' },
  { bit: 1, name: '仅对施法者触发' },
  { bit: 2, name: '离线时继续计时' },
  { bit: 3, name: '无增益威胁值' },
  { bit: 4, name: '无减益威胁值' },
  { bit: 5, name: '允许客户端选择目标' },
  { bit: 6, name: '无法被偷取' },
  { bit: 7, name: '允许施法时施法/被触发' },
  { bit: 8, name: '固定伤害/忽略受到伤害修正（如格挡）' },
  { bit: 9, name: '从事件激活/可用时战斗反馈' },
  { bit: 10, name: '法术对扩展消耗/武器速度消耗缩放' },
  { bit: 11, name: '无部分免疫' },
  { bit: 12, name: '光环为增益效果' },
  { bit: 13, name: '不记录施法者' },
  { bit: 14, name: '伤害不打断光环/反伤触发' },
  { bit: 15, name: '不在法术书中' },
  { bit: 16, name: '竞技场中无法使用' },
  { bit: 17, name: '竞技场中可用' },
  { bit: 18, name: '弹跳连锁飞弹' },
  { bit: 19, name: '允许坐下时触发' },
  { bit: 20, name: '不检查自我施法能量/光环永不弹跳' },
  { bit: 21, name: '允许进入竞技场' },
  { bit: 22, name: '触发时抑制攻击动画' },
  { bit: 23, name: '抑制武器触发' },
  { bit: 24, name: '自动远程战斗' },
  { bit: 25, name: '宠物缩放/所有者能量缩放' },
  { bit: 26, name: '仅限飞行区域使用' },
  { bit: 27, name: '强制显示施法条' },
  { bit: 28, name: '忽略战斗计时器' },
  { bit: 29, name: '光环弹跳导致法术失败' },
  { bit: 30, name: '已过时' },
  { bit: 31, name: '使用法术朝向' },
];

SPELL_DBC_ATTRIBUTES_FLAGS['Ex5'] = [
  { bit: 0, name: '引导时允许其他动作' },
  { bit: 1, name: '光环存在时无材料消耗' },
  { bit: 2, name: '进入竞技场时移除' },
  { bit: 3, name: '昏迷时允许' },
  { bit: 4, name: '触发引导' },
  { bit: 5, name: '单体法术/限制数量' },
  { bit: 6, name: '忽略范围效果PvP检查' },
  { bit: 7, name: '不能对玩家使用' },
  { bit: 8, name: '不能对玩家控制的NPC使用' },
  { bit: 9, name: '光环应用时开始周期/额外初始周期' },
  { bit: 10, name: '不显示持续时间' },
  { bit: 11, name: '允许目标的目标作为目标/隐含目标' },
  { bit: 12, name: '近战连锁目标（顺劈）' },
  { bit: 13, name: '法术急速影响周期（持续时间）' },
  { bit: 14, name: '魅惑时无法使用' },
  { bit: 15, name: '视为范围效果（影响多个目标）' },
  { bit: 16, name: '光环影响不仅限于需求装备' },
  { bit: 17, name: '恐惧时允许' },
  { bit: 18, name: '混乱时允许' },
  { bit: 19, name: 'AI不面向目标/施法时不转向' },
  { bit: 20, name: '下马时不尝试重新召唤宠物' },
  { bit: 21, name: '忽略目标要求' },
  { bit: 22, name: '不对低级目标使用' },
  { bit: 23, name: '无部分抵抗' },
  { bit: 24, name: '忽略施法者要求' },
  { bit: 25, name: '总是需要视线' },
  { bit: 26, name: '范围效果总是需要视线' },
  { bit: 27, name: '无施法者光环图标' },
  { bit: 28, name: '无目标光环图标' },
  { bit: 29, name: '每个施法者光环唯一' },
  { bit: 30, name: '总是显示地面材质' },
  { bit: 31, name: '添加近战命中率/范围嘲讽' },
];

SPELL_DBC_ATTRIBUTES_FLAGS['Ex6'] = [
  { bit: 0, name: '提示中不显示冷却时间' },
  { bit: 1, name: '竞技场中不重置冷却' },
  { bit: 2, name: '非攻击/忽略施法者光环' },
  { bit: 3, name: '可协助免疫玩家/协助忽略免疫标志' },
  { bit: 4, name: '忽略时间速率修改' },
  { bit: 5, name: '不消耗资源' },
  { bit: 6, name: '施法时显示浮动战斗文字' },
  { bit: 7, name: '光环为武器触发' },
  { bit: 8, name: '不连锁到被控制目标' },
  { bit: 9, name: '允许对被魅惑目标使用' },
  { bit: 10, name: '无光环记录' },
  { bit: 11, name: '不在团队副本中' },
  { bit: 12, name: '允许骑乘载具时使用' },
  { bit: 13, name: '可选择隐形目标/忽略相位转换' },
  { bit: 14, name: 'AI主要远程攻击' },
  { bit: 15, name: '无施法推移' },
  { bit: 16, name: '无跳跃寻路' },
  { bit: 17, name: '允许施法时装备' },
  { bit: 18, name: '来源于控制者' },
  { bit: 19, name: '施法时延迟战斗计时器' },
  { bit: 20, name: '光环图标仅对施法者显示（限制10个）' },
  { bit: 21, name: '显示机制为战斗文字' },
  { bit: 22, name: '吸收无法被忽略' },
  { bit: 23, name: '立即标记' },
  { bit: 24, name: '可选择无法选择的目标' },
  { bit: 25, name: '瞬发时不重置攻击计时器' },
  { bit: 26, name: '载具免疫类别' },
  { bit: 27, name: '忽略治疗修正' },
  { bit: 28, name: '不自动选择开始战斗的目标' },
  { bit: 29, name: '忽略施法者伤害修正' },
  { bit: 30, name: '禁用关联效果点数' },
  { bit: 31, name: '无类别冷却修改' },
];

SPELL_DBC_ATTRIBUTES_FLAGS['Ex7'] = [
  { bit: 0, name: '允许法术反射/假死' },
  { bit: 1, name: '无目标持续时间修正' },
  { bit: 2, name: '死亡时禁用光环' },
  { bit: 3, name: '作弊法术/调试法术' },
  { bit: 4, name: '视为团队增益' },
  { bit: 5, name: '可多重施放（图腾）' },
  { bit: 6, name: '不造成法术推移' },
  { bit: 7, name: '准备结束载具控制' },
  { bit: 8, name: '仅限部落' },
  { bit: 9, name: '仅限联盟' },
  { bit: 10, name: '驱散移除层数' },
  { bit: 11, name: '可造成打断（仅打断非玩家）' },
  { bit: 12, name: '可造成沉默' },
  { bit: 13, name: '无界面不可打断' },
  { bit: 14, name: '重新召唤时重施（复活）' },
  { bit: 15, name: '法术开始时重置攻击计时器' },
  { bit: 16, name: '学习前仅在法术书中（恢复次要能量）' },
  { bit: 17, name: '不记录PvP击杀' },
  { bit: 18, name: '冲锋到单位时攻击' },
  { bit: 19, name: '向目标单位报告法术失败（区域传送）' },
  { bit: 20, name: '昏迷、恐惧、混乱时客户端不失败（闪现、圣盾、寒冰屏障）' },
  { bit: 21, name: '加载时保留冷却' },
  { bit: 22, name: '忽略寒冷天气飞行需求' },
  { bit: 23, name: '无法躲闪攻击' },
  { bit: 24, name: '无法招架攻击' },
  { bit: 25, name: '无法未命中攻击' },
  { bit: 26, name: '视为NPC范围效果' },
  { bit: 27, name: '绕过无法复活光环' },
  { bit: 28, name: '不计入PvP记分板/合并团队增益' },
  { bit: 29, name: '反射仅防御' },
  { bit: 30, name: '可从被抑制的目标触发中触发' },
  { bit: 31, name: '总是记录施法/客户端指示器' },
];
