import { Flag } from '@keira/shared/constants';

export const UNIT_FLAGS: Flag[] = [
  { bit: 0, name: '服务器控制' },
  { bit: 1, name: '无法被攻击 - 不能被玩家或NPC攻击，但仍可攻击玩家' },
  { bit: 2, name: '禁止移动' },
  { bit: 3, name: '玩家控制 - 被玩家控制，使用_IMMUNE_TO_PC代替_IMMUNE_TO_NPC' },
  { bit: 4, name: '重命名' },
  { bit: 5, name: '准备状态 - 在有SPELL_ATTR5_NO_REAGENT_WHILE_PREP属性的法术不消耗施法材料' },
  { bit: 6, name: '未知_6 - 作用不明，但在智能脚本中施放非触发法术时需要' },
  { bit: 7, name: '无法被攻击_1 - 不能被玩家或NPC攻击，但仍可攻击玩家' },
  { bit: 8, name: '免疫玩家 - 禁用与玩家角色的战斗/援助' },
  { bit: 9, name: '免疫NPC - 禁用与非玩家角色的战斗/援助' },
  { bit: 10, name: '拾取中 - 拾取动画' },
  { bit: 11, name: '宠物战斗中' },
  { bit: 12, name: '玩家对战' },
  { bit: 13, name: '沉默 - 无法施法' },
  { bit: 14, name: '未知_14' },
  { bit: 15, name: '未知_15 - 仅游泳' },
  { bit: 16, name: '未知_16 - 无法攻击2 - 不能被玩家或NPC攻击，但仍可攻击玩家' },
  { bit: 17, name: '平和 - 生物不会攻击' },
  { bit: 18, name: '昏迷' },
  { bit: 19, name: '战斗中' },
  { bit: 20, name: '飞行坐骑 - 在客户端禁用飞行时不允许的法术' },
  { bit: 21, name: '缴械 - 禁用近战法术施放' },
  { bit: 22, name: '混乱' },
  { bit: 23, name: '逃跑 - 恐惧状态' },
  { bit: 24, name: '被控制 - 被玩家直接控制（支配或载具）' },
  {
    bit: 25,
    name: '不可选中 - 不显示名字文本和姓名板，无法用鼠标选中或使用 /target {名字} 命令',
  },
  { bit: 26, name: '可剥皮' },
  { bit: 27, name: '坐骑 - 客户端完美处理。也用于制作自定义坐骑' },
  { bit: 28, name: '未知_28 - 拾取时防止下跪' },
  {
    bit: 29,
    name: '禁止聊天表情 - 阻止自动解析聊天文本播放表情，例如在/说中的"哈哈"，以?或!结尾的消息，或使用/大喊',
  },
  { bit: 30, name: '收起武器' },
  { bit: 31, name: '未知_31' },
];
