import { Option } from '@keira/shared/constants';

export const CREATURE_RACE: Option[] = [
  { value: 0, name: '无' },
  { value: 1, name: '人类' },
  { value: 2, name: '兽人' },
  { value: 3, name: '矮人' },
  { value: 4, name: '暗夜精灵' },
  { value: 5, name: '亡灵' },
  { value: 6, name: '牛头人' },
  { value: 7, name: '侏儒' },
  { value: 8, name: '巨魔' },
  { value: 9, name: '地精（未使用）' },
  { value: 10, name: '血精灵' },
  { value: 11, name: '德莱尼' },
  { value: 12, name: '堕落兽人（未使用）' },
  { value: 13, name: '娜迦（未使用）' },
  { value: 14, name: '破碎者（未使用）' },
  { value: 15, name: '骷髅（未使用）' },
  { value: 16, name: '维库人（未使用）' },
  { value: 17, name: '海象人（未使用）' },
  { value: 18, name: '森林巨魔（未使用）' },
  { value: 19, name: '牦牛人（未使用）' },
  { value: 20, name: '诺森德骷髅（未使用）' },
];
