import { Option } from '@keira/shared/constants';

export const SPELL_DBC_EFFECT: Option[] = [
  { value: 0, name: '无' },
  { value: 1, name: '瞬间击杀' },
  { value: 2, name: '法术伤害' },
  { value: 3, name: '假人' },
  { value: 4, name: '传送门传送 未使用' },
  { value: 5, name: '传送单位' },
  { value: 6, name: '应用光环' },
  { value: 7, name: '环境伤害' },
  { value: 8, name: '能量吸取' },
  { value: 9, name: '生命吸取' },
  { value: 10, name: '治疗' },
  { value: 11, name: '绑定' },
  { value: 12, name: '传送门' },
  { value: 13, name: '仪式基础 未使用' },
  { value: 14, name: '仪式专精 未使用' },
  { value: 15, name: '激活传送门仪式 未使用' },
  { value: 16, name: '任务完成' },
  { value: 17, name: '无学派武器伤害' },
  { value: 18, name: '复活' },
  { value: 19, name: '额外攻击次数' },
  { value: 20, name: '闪躲 仅一个法术：闪躲' },
  { value: 21, name: '躲避 仅一个法术：躲避(DND)' },
  { value: 22, name: '招架' },
  { value: 23, name: '格挡 仅一个法术：格挡' },
  { value: 24, name: '创造物品' },
  { value: 25, name: '武器' },
  { value: 26, name: '防御 仅一个法术：防御' },
  { value: 27, name: '持续区域光环' },
  { value: 28, name: '召唤' },
  { value: 29, name: '跳跃' },
  { value: 30, name: '能量获取' },
  { value: 31, name: '武器百分比伤害' },
  { value: 32, name: '触发飞弹' },
  { value: 33, name: '开锁' },
  { value: 34, name: '召唤改变物品' },
  { value: 35, name: '应用小队区域光环' },
  { value: 36, name: '学习法术' },
  { value: 37, name: '法术防御 仅一个法术：法术防御(DND)' },
  { value: 38, name: '驱散' },
  { value: 39, name: '语言' },
  { value: 40, name: '双持' },
  { value: 41, name: '跳跃' },
  { value: 42, name: '跳跃目的地' },
  { value: 43, name: '传送单位面向施法者' },
  { value: 44, name: '技能等级' },
  { value: 45, name: '增加荣誉 荣誉/PVP相关' },
  { value: 46, name: '出生 客户端，单位显示为刚刚生成' },
  { value: 47, name: '商业技能' },
  { value: 48, name: '潜行 仅一个法术：基础潜行' },
  { value: 49, name: '侦测 仅一个法术：侦测' },
  { value: 50, name: '传送门' },
  { value: 51, name: '强制暴击 未使用' },
  { value: 52, name: '保证命中 仅一个法术：旧版暴击射击' },
  { value: 53, name: '附魔物品' },
  { value: 54, name: '临时附魔物品' },
  { value: 55, name: '驯服生物' },
  { value: 56, name: '召唤宠物' },
  { value: 57, name: '学习宠物技能' },
  { value: 58, name: '武器伤害' },
  { value: 59, name: '创造随机物品 根据法术特定掉落创建物品' },
  { value: 60, name: '熟练度' },
  { value: 61, name: '发送事件' },
  { value: 62, name: '能量燃烧' },
  { value: 63, name: '威胁值' },
  { value: 64, name: '触发法术' },
  { value: 65, name: '应用团队区域光环' },
  { value: 66, name: '创造法力宝石 (可能是充能，misc为物品ID)' },
  { value: 67, name: '治疗最大生命值' },
  { value: 68, name: '打断施法' },
  { value: 69, name: '分散注意力' },
  { value: 70, name: '拉扯 仅一个法术：分散移动' },
  { value: 71, name: '偷窃' },
  { value: 72, name: '添加远视' },
  { value: 73, name: '遗忘天赋' },
  { value: 74, name: '应用雕文' },
  { value: 75, name: '修理机械 仅一个法术：机械修理包' },
  { value: 76, name: '召唤野生物体' },
  { value: 77, name: '脚本效果' },
  { value: 78, name: '攻击' },
  { value: 79, name: '庇护' },
  { value: 80, name: '增加连击点数' },
  { value: 81, name: '创建房屋 仅一个法术：创建房屋(测试)' },
  { value: 82, name: '绑定视野' },
  { value: 83, name: '决斗' },
  { value: 84, name: '卡住' },
  { value: 85, name: '召唤玩家' },
  { value: 86, name: '激活物体' },
  { value: 87, name: '游戏对象伤害' },
  { value: 88, name: '游戏对象修理' },
  { value: 89, name: '设置游戏对象破坏状态' },
  { value: 90, name: '击杀统计 仅限单人' },
  { value: 91, name: '全体威胁 仅一个法术：旧版洗脑' },
  { value: 92, name: '附魔持有物品' },
  { value: 93, name: '强制取消选择' },
  { value: 94, name: '自我复活' },
  { value: 95, name: '剥皮' },
  { value: 96, name: '冲锋' },
  { value: 97, name: '施法按钮 (3.2.2a起为图腾栏)' },
  { value: 98, name: '击退' },
  { value: 99, name: '分解' },
  { value: 100, name: '醉酒' },
  { value: 101, name: '喂养宠物' },
  { value: 102, name: '解散宠物' },
  { value: 103, name: '声望' },
  { value: 104, name: '召唤物品栏1' },
  { value: 105, name: '召唤物品栏2' },
  { value: 106, name: '召唤物品栏3' },
  { value: 107, name: '召唤物品栏4' },
  { value: 108, name: '驱散机制' },
  { value: 109, name: '召唤死亡宠物' },
  { value: 110, name: '摧毁所有图腾' },
  { value: 111, name: '耐久度伤害' },
  { value: 112, name: '112 未使用' },
  { value: 113, name: '新版复活' },
  { value: 114, name: '攻击我' },
  { value: 115, name: '耐久度百分比伤害' },
  { value: 116, name: '剥皮玩家尸体 仅一个法术：移除徽记，战场用，需要特殊尸体标记' },
  { value: 117, name: '灵魂治疗 仅一个法术：灵魂治疗' },
  { value: 118, name: '技能 专业和更多' },
  { value: 119, name: '应用宠物区域光环' },
  { value: 120, name: '传送墓地 仅一个法术：墓地传送测试' },
  { value: 121, name: '标准化武器伤害' },
  { value: 122, name: '122 未使用' },
  { value: 123, name: '发送飞行坐骑 飞行/坐骑相关 (misc值为飞行路径ID)' },
  { value: 124, name: '向前拉' },
  { value: 125, name: '修改威胁值百分比' },
  { value: 126, name: '偷取有益效果 法术偷取效果?' },
  { value: 127, name: '勘探 勘探法术' },
  { value: 128, name: '应用友方区域光环' },
  { value: 129, name: '应用敌方区域光环' },
  { value: 130, name: '重定向威胁' },
  { value: 131, name: '玩家通知 misc值为音效ID (SoundEntries.dbc)' },
  { value: 132, name: '播放音乐 misc值为音效ID (SoundEntries.dbc)' },
  { value: 133, name: '遗忘专精 遗忘专业专精' },
  { value: 134, name: '击杀统计 misc值为生物条目' },
  { value: 135, name: '召唤宠物' },
  { value: 136, name: '治疗百分比' },
  { value: 137, name: '能量百分比' },
  { value: 138, name: '向后跳跃 向后跳' },
  { value: 139, name: '清除任务 重置任务状态 (miscValue - 任务ID)' },
  { value: 140, name: '强制施法' },
  { value: 141, name: '带数值强制施法' },
  { value: 142, name: '带数值触发法术' },
  { value: 143, name: '应用所有者区域光环' },
  { value: 144, name: '击退到目的地' },
  { value: 145, name: '拉向目的地 黑洞效果' },
  { value: 146, name: '激活符文' },
  { value: 147, name: '任务失败 任务失败' },
  { value: 148, name: '带数值触发飞弹法术' },
  { value: 149, name: '冲锋到目的地' },
  { value: 150, name: '开始任务' },
  { value: 151, name: '触发法术2' },
  { value: 152, name: '召唤推荐好友 召唤推荐好友' },
  { value: 153, name: '创建已驯服宠物 misc值为生物条目' },
  { value: 154, name: '发现飞行点' },
  {
    value: 155,
    name: '泰坦之握 允许你单手装备双手斧、锤和剑，但攻击速度降低$49152s1%。',
  },
  { value: 156, name: '棱彩附魔物品' },
  { value: 157, name: '创造物品2 创建物品或创建物品模板并替换为某些随机法术掉落物品' },
  { value: 158, name: '研磨 研磨' },
  { value: 159, name: '允许重命名宠物 再次允许重命名宠物' },
  { value: 160, name: '1个法术示例 - 45534' },
  { value: 161, name: '天赋专精计数 第二天赋专精(学习/还原)' },
  { value: 162, name: '天赋专精选择 激活主要/次要专精' },
  { value: 163, name: '未使用' },
  { value: 164, name: '移除光环' },
  { value: 26, name: '定身' },
  { value: 27, name: '沉默' },
  { value: 28, name: '法术反射' },
  { value: 29, name: '属性修正' },
  { value: 30, name: '技能修正' },
  { value: 31, name: '移动速度提高' },
  { value: 32, name: '坐骑速度提高' },
  { value: 33, name: '移动速度降低' },
  { value: 34, name: '生命值提高' },
  { value: 35, name: '能量值提高' },
  { value: 36, name: '变形' },
  { value: 37, name: '效果免疫' },
  { value: 38, name: '状态免疫' },
  { value: 39, name: '法术学派免疫' },
  { value: 40, name: '伤害免疫' },
  { value: 41, name: '驱散免疫' },
  { value: 42, name: '触发法术' },
  { value: 43, name: '触发伤害' },
  { value: 44, name: '追踪生物' },
  { value: 45, name: '追踪资源' },
  { value: 46, name: '光环46' },
  { value: 47, name: '招架几率修正' },
  { value: 48, name: '光环48' },
  { value: 49, name: '闪避几率修正' },
  { value: 50, name: '治疗暴击效果修正' },
  { value: 51, name: '格挡几率修正' },
  { value: 52, name: '武器暴击几率修正' },
  { value: 53, name: '周期性吸取' },
  { value: 54, name: '命中几率修正' },
  { value: 55, name: '法术命中几率修正' },
  { value: 56, name: '变形' },
  { value: 57, name: '法术暴击几率修正' },
  { value: 58, name: '游泳速度提高' },
  { value: 59, name: '对生物伤害修正' },
  { value: 60, name: '沉默和平和' },
  { value: 61, name: '体型修正' },
  { value: 62, name: '周期性生命通道' },
  { value: 63, name: '光环63' },
  { value: 64, name: '周期性法力吸取' },
  { value: 65, name: '施法速度修正(不叠加)' },
  { value: 66, name: '假死' },
  { value: 67, name: '缴械' },
  { value: 68, name: '被追踪' },
  { value: 69, name: '法术吸收' },
  { value: 70, name: '额外攻击次数' },
  { value: 71, name: '法术学派暴击几率修正' },
  { value: 72, name: '法术学派能量消耗百分比' },
  { value: 73, name: '法术学派能量消耗' },
  { value: 74, name: '法术学派反射' },
  { value: 75, name: '语言修正' },
  { value: 76, name: '远视' },
  { value: 77, name: '机制免疫' },
  { value: 78, name: '坐骑' },
  { value: 79, name: '伤害百分比修正' },
  { value: 80, name: '属性百分比修正' },
  { value: 81, name: '伤害分摊百分比' },
  { value: 82, name: '水下呼吸' },
  { value: 83, name: '基础抗性修正' },
  { value: 84, name: '回复修正' },
  { value: 85, name: '能量回复修正' },
  { value: 86, name: '死亡物品通道' },
  { value: 87, name: '受到伤害百分比修正' },
  { value: 88, name: '生命回复百分比修正' },
  { value: 89, name: '周期性伤害百分比' },
  { value: 90, name: '光环90' },
  { value: 91, name: '侦测范围修正' },
  { value: 92, name: '防止逃跑' },
  { value: 93, name: '无法攻击' },
  { value: 94, name: '中断回复' },
  { value: 95, name: '灵魂状态' },
  { value: 96, name: '法术磁石' },
  { value: 97, name: '法力护盾' },
  { value: 98, name: '技能天赋修正' },
  { value: 99, name: '攻击强度修正' },
  { value: 100, name: '光环可见' },
  { value: 101, name: '抗性百分比修正' },
  { value: 102, name: '对特定目标近战攻击强度修正' },
  { value: 103, name: '总威胁值修正' },
  { value: 104, name: '水上行走' },
  { value: 105, name: '缓落' },
  { value: 106, name: '悬浮' },
  { value: 107, name: '添加固定修正' },
  { value: 108, name: '添加百分比修正' },
  { value: 109, name: '添加目标触发' },
  { value: 110, name: '能量回复百分比修正' },
  { value: 111, name: '添加施法者命中触发' },
  { value: 112, name: '覆盖职业脚本' },
  { value: 113, name: '远程伤害承受修正' },
  { value: 114, name: '远程伤害承受百分比修正' },
  { value: 115, name: '治疗效果修正' },
  { value: 116, name: '战斗中回复修正' },
  { value: 117, name: '机制抗性修正' },
  { value: 118, name: '治疗效果百分比修正' },
  { value: 119, name: '光环119' },
  { value: 120, name: '无法追踪' },
  { value: 121, name: '共情' },
  { value: 122, name: '副手伤害百分比' },
  { value: 123, name: '目标抗性' },
  { value: 124, name: '远程攻击强度' },
  { value: 125, name: '近战伤害承受' },
  { value: 126, name: '近战伤害承受百分比' },
  { value: 127, name: '远程攻击强度攻击者加成' },
  { value: 128, name: '控制宠物' },
  { value: 129, name: '永久移动速度' },
  { value: 130, name: '永久坐骑速度' },
  { value: 131, name: '目标远程攻击强度' },
  { value: 132, name: '能量值百分比' },
  { value: 133, name: '生命值百分比' },
  { value: 134, name: '法力回复中断' },
  { value: 135, name: '治疗效果' },
  { value: 136, name: '治疗效果百分比' },
  { value: 137, name: '属性总值百分比' },
  { value: 138, name: '近战急速' },
  { value: 139, name: '强制声望' },
  { value: 140, name: '远程急速' },
  { value: 141, name: '弹药急速' },
  { value: 142, name: '基础抗性百分比' },
  { value: 143, name: '专属抗性' },
  { value: 144, name: '安全降落' },
  { value: 145, name: '宠物天赋点数' },
  { value: 146, name: '允许驯服宠物类型' },
  { value: 147, name: '机制免疫掩码' },
  { value: 148, name: '连击点保留' },
  { value: 149, name: '施法推移减免' },
  { value: 150, name: '盾牌格挡值百分比' },
  { value: 151, name: '追踪潜行' },
  { value: 152, name: '侦测范围' },
  { value: 153, name: '伤害分摊固定值' },
  { value: 154, name: '潜行等级' },
  { value: 155, name: '水下呼吸' },
  { value: 156, name: '声望获取' },
  { value: 157, name: '宠物伤害倍数' },
  { value: 158, name: '盾牌格挡值' },
  { value: 159, name: '无PvP荣誉' },
  { value: 160, name: '范围效果躲避' },
  { value: 161, name: '战斗中生命回复' },
  { value: 162, name: '能量燃烧' },
  { value: 163, name: '暴击伤害加成' },
  { value: 164, name: '光环164' },
  { value: 165, name: '近战攻击强度攻击者加成' },
  { value: 166, name: '攻击强度百分比' },
  { value: 167, name: '远程攻击强度百分比' },
  { value: 168, name: '目标伤害加成' },
  { value: 169, name: '目标暴击几率' },
  { value: 170, name: '侦测隐形' },
  { value: 171, name: '移动速度不叠加' },
  { value: 172, name: '坐骑速度不叠加' },
  { value: 173, name: '光环173' },
  { value: 174, name: '属性法术伤害百分比' },
  { value: 175, name: '属性法术治疗百分比' },
  { value: 176, name: '救赎之魂' },
  { value: 177, name: '范围魅惑' },
  { value: 178, name: '负面效果抗性' },
  { value: 179, name: '攻击者法术暴击' },
  { value: 180, name: '目标法术伤害固定值' },
  { value: 181, name: '光环181' },
  { value: 182, name: '属性抗性百分比' },
  { value: 183, name: '仇恨值修正' },
  { value: 184, name: '攻击者近战命中' },
  { value: 185, name: '攻击者远程命中' },
  { value: 186, name: '攻击者法术命中' },
  { value: 187, name: '攻击者近战暴击' },
  { value: 188, name: '攻击者远程暴击' },
  { value: 189, name: '战斗评级' },
  { value: 190, name: '阵营声望获取' },
  { value: 191, name: '正常移动速度' },
  { value: 192, name: '近战远程急速' },
  { value: 193, name: '近战减速' },
  { value: 194, name: '目标法术吸收' },
  { value: 195, name: '目标技能吸收' },
  { value: 196, name: '冷却时间' },
  { value: 197, name: '攻击者法术武器暴击' },
  { value: 198, name: '光环198' },
  { value: 199, name: '法术命中几率' },
  { value: 200, name: '经验获取' },
  { value: 201, name: '飞行' },
  { value: 202, name: '忽略战斗结果' },
  { value: 203, name: '攻击者近战暴击伤害' },
  { value: 204, name: '攻击者远程暴击伤害' },
  { value: 205, name: '法术暴击伤害承受' },
  { value: 206, name: '载具飞行速度' },
  { value: 207, name: '坐骑飞行速度' },
  { value: 208, name: '飞行速度' },
  { value: 209, name: '永久坐骑飞行速度' },
  { value: 210, name: '永久载具速度' },
  { value: 211, name: '飞行速度不叠加' },
  { value: 212, name: '属性远程攻击强度百分比' },
  { value: 213, name: '伤害产生怒气' },
  { value: 214, name: '光环214' },
  { value: 215, name: '竞技场准备' },
  { value: 216, name: '法术急速' },
  { value: 217, name: '近战急速2' },
  { value: 218, name: '远程急速' },
  { value: 219, name: '属性法力回复' },
  { value: 220, name: '属性战斗评级' },
  { value: 221, name: '嘲讽值' },
  { value: 222, name: '光环222' },
  { value: 223, name: '团队充能触发' },
  { value: 224, name: '光环224' },
  { value: 225, name: '团队充能数值触发' },
  { value: 226, name: '周期性虚拟效果' },
  { value: 227, name: '周期性数值法术触发' },
  { value: 228, name: '侦测潜行' },
  { value: 229, name: '范围伤害躲避' },
  { value: 230, name: '光环230' },
  { value: 231, name: '数值法术触发' },
  { value: 232, name: '机制持续时间' },
  { value: 233, name: '所有人型生物模型' },
  { value: 234, name: '机制持续时间不叠加' },
  { value: 235, name: '驱散抗性' },
  { value: 236, name: '控制载具' },
  { value: 237, name: '攻击强度法术伤害' },
  { value: 238, name: '攻击强度法术治疗' },
  { value: 239, name: '体型缩放2' },
  { value: 240, name: '精准等级' },
  { value: 241, name: '强制向前移动' },
  { value: 242, name: '治疗转化伤害' },
  { value: 243, name: '阵营修改' },
  { value: 244, name: '语言理解' },
  { value: 245, name: '驱散光环持续时间' },
  { value: 246, name: '驱散光环持续时间不叠加' },
  { value: 247, name: '复制施法者' },
  { value: 248, name: '战斗结果几率' },
  { value: 249, name: '转化符文' },
  { value: 250, name: '生命值提高2' },
  { value: 251, name: '敌人闪避' },
  { value: 252, name: '全体减速' },
  { value: 253, name: '格挡暴击几率' },
  { value: 254, name: '缴械副手' },
  { value: 255, name: '机制伤害承受百分比' },
  { value: 256, name: '无需施法材料' },
  { value: 257, name: '法术类型目标抗性' },
  { value: 258, name: '光环258' },
  { value: 259, name: '持续治疗效果' },
  { value: 260, name: '屏幕效果' },
  { value: 261, name: '相位' },
  { value: 262, name: '忽略光环状态' },
  { value: 263, name: '仅允许技能' },
  { value: 264, name: '光环264' },
  { value: 265, name: '光环265' },
  { value: 266, name: '光环266' },
  { value: 267, name: '法术学派光环免疫' },
  { value: 268, name: '属性攻击强度百分比' },
  { value: 269, name: '忽略目标抗性' },
  { value: 270, name: '技能忽略目标抗性' },
  { value: 271, name: '施法者伤害修正' },
  { value: 272, name: '忽略近战重置' },
  { value: 273, name: 'X光透视' },
  { value: 274, name: '技能无需弹药' },
  { value: 275, name: '忽略变形' },
  { value: 276, name: '机制伤害加成' },
  { value: 277, name: '最大目标数量' },
  { value: 278, name: '缴械远程武器' },
  { value: 279, name: '初始化图像' },
  { value: 280, name: '护甲穿透百分比' },
  { value: 281, name: '荣誉获取百分比' },
  { value: 282, name: '基础生命值百分比' },
  { value: 283, name: '受到治疗效果' },
  { value: 284, name: '关联' },
  { value: 285, name: '护甲攻击强度' },
  { value: 286, name: '周期性技能暴击' },
  { value: 287, name: '法术偏转' },
  { value: 288, name: '忽略命中方向' },
  { value: 289, name: '光环289' },
  { value: 290, name: '暴击几率' },
  { value: 291, name: '任务经验百分比' },
  { value: 292, name: '打开马厩' },
  { value: 293, name: '覆盖法术' },
  { value: 294, name: '阻止能量恢复' },
  { value: 295, name: '光环295' },
  { value: 296, name: '设置载具ID' },
  { value: 297, name: '阻止法术系' },
  { value: 298, name: '绞杀' },
  { value: 299, name: '光环299' },
  { value: 300, name: '伤害分摊百分比' },
  { value: 301, name: '法术治疗吸收' },
  { value: 302, name: '光环302' },
  { value: 303, name: '光环状态伤害加成' },
  { value: 304, name: '醉酒程度' },
  { value: 305, name: '最低速度' },
  { value: 306, name: '光环306' },
  { value: 307, name: '治疗吸收测试' },
  { value: 308, name: '施法者暴击几率' },
  { value: 309, name: '光环309' },
  { value: 310, name: '生物范围伤害躲避' },
  { value: 311, name: '光环311' },
  { value: 312, name: '光环312' },
  { value: 313, name: '光环313' },
  { value: 314, name: '阻止复活' },
  { value: 315, name: '水上行走' },
  { value: 316, name: '周期性急速' },
];
